apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: default
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "myapp-role"
    vault.hashicorp.com/agent-inject-secret-myapp.txt: "secret/myapp"
    vault.hashicorp.com/template-static-secret-render-interval: "5s"
    vault.hashicorp.com/agent-inject-template-myapp.txt: |
      {{ with secret "secret/data/myapp" -}}
      {{ range $k, $v := .Data.data }}
      {{ $k }}={{ $v }}
      {{ end }}
      {{- end }}
  labels:
    app: vault-agent-injector-test
spec:
  serviceAccountName: myapp-sa
  containers:
  - name: myapp
    image: nginx
