global:
  ## ldapDomain , can be explicit (e.g dc=toto,c=ca) or domain based (e.g example.com)
  ldapDomain: "example.org"
  # Specifies an existing secret to be used for admin and config user passwords. The expected key are LDAP_ADMIN_PASSWORD and LDAP_CONFIG_ADMIN_PASSWORD.
  # existingSecret: ""
  ## Default Passwords to use, stored as a secret. Not used if existingSecret is set.
  adminUser: "admin"
  adminPassword: Not@SecurePassw0rd
  configUser: "admin"
  configPassword: Not@SecurePassw0rd

# image:
#   # From repository https://github.com/osixia/docker-openldap
#   repository: osixia/openldap
#   tag: 1.2.4
#   pullPolicy: IfNotPresent

# Spcifies an existing secret to be used for admin and config user passwords
existingSecret: ""

logLevel: debug
replicaCount: 1

# Custom openldap configuration files used to override default settings
# customLdifFiles:
#   0-initial-ous.ldif: |-
#     dn: ou=People,dc=example,dc=org
#     objectClass: organizationalUnit
#     ou: People

#     dn: ou=Group,dc=example,dc=org
#     objectClass: organizationalUnit
#     ou: Group

# settings for enabling TLS
tls:
  enabled: false
  secret: ""  # The name of a kubernetes.io/tls type secret to use for TLS
  CA:
    enabled: false
    secret: ""  # The name of a generic secret to use for custom CA certificate (ca.crt)

env:
  LDAP_ORGANISATION: "example"
  LDAP_DOMAIN: "example.org"
  LDAP_BACKEND: "hdb"
  LDAP_TLS: "true"
  LDAP_TLS_ENFORCE: "false"
  LDAP_READONLY_USER: "true"


## ltb-passwd
# For more parameters check following file: ./charts/ltb-passwd/values.yaml
ltb-passwd:
  enabled : true
  ingress:
    enabled: false

## phpldapadmin
## For more parameters check following file: ./charts/phpldapadmin/values.yaml
phpldapadmin:
  enabled: true 
  ingress:
    enabled: false 


## Persist data to a persistent volume
persistence: {}
  # enabled: false
  # ## database data Persistent Volume Storage Class
  # ## If defined, storageClassName: <storageClass>
  # ## If set to "-", storageClassName: "", which disables dynamic provisioning
  # ## If undefined (the default) or set to null, no storageClassName spec is
  # ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  # ##   GKE, AWS & OpenStack)
  # ##
  # # storageClass: "-"
  # accessMode: ReadWriteOnce
  # size: 8Gi
  # # existingClaim: ""

resources: {}
 # requests:
 #   cpu: "100m"
 #   memory: "256Mi"
 # limits:
 #   cpu: "500m"
 #   memory: "512Mi"

initResources: {}
 # requests:
 #   cpu: "100m"
 #   memory: "128Mi"
 # limits:
 #   cpu: "100m"
 #   memory: "128Mi"

nodeSelector: {}

tolerations: []

affinity: {}