demo_files:
#- ldap.sh
#- dynamic_secret_ssh.sh
- dynamic_secret_k8s.sh
- vault_secret_operator.sh
- sentinel_policies.sh
- vault_monitoring.sh 
- vault_automaic_backups.sh 
- vault_agent_deployment.sh 
- pki.sh
