grafana:
  enabled: true
  adminPassword: password
  forceDeployDashboards: true
  defaultDashboardsEnabled: false
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /var/lib/grafana/dashboards
      updateIntervalSeconds: 10
      folderAnnotation: grafana_folder
      provider:
        allowUiUpdates: true
        foldersFromFilesStructure: true

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    # Mount the secret containing the prometheus-token
    volumes:
      - name: prometheus-token
        secret:
          secretName: prometheus-token

    volumeMounts:
      - name: prometheus-token
        mountPath: /etc/prometheus/prometheus-token
        subPath: prometheus-token
        readOnly: true

    additionalScrapeConfigs: |
      - job_name: vault
        metrics_path: /v1/sys/metrics
        params:
          format: ['prometheus']
        scheme: http
        authorization:
          credentials_file: /etc/prometheus/prometheus-token
        static_configs:
        - targets: ['vault.vault.svc.cluster.local:8200']


kubeStateMetrics:
  enabled: true
